# Generated by Django 3.2.9 on 2022-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optional_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
