# Generated by Django 3.2.9 on 2022-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_optional_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(None, 'Quiz Type'), ('checkbox', 'Checkbox'), ('text', 'Input'), ('number', 'Number'), ('radio', 'Radio'), ('textarea', 'Textarea'), ('url', 'URL')], max_length=10),
        ),
    ]
