# Generated by Django 3.2.9 on 2022-03-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='percent_correct',
            field=models.IntegerField(default='0'),
        ),
    ]
