# Generated by Django 3.2.9 on 2022-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('is_mentor', 'Quiz for Mentors'), ('is_not_mentor', 'Quiz for Potential Mentors')], max_length=20)),
                ('max_count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
