# Generated by Django 3.2.9 on 2022-10-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('is_mentor', 'Quiz for Mentors'), ('is_not_mentor', 'Quiz for Potential Mentors')], default='is_not_mentor', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
