# Generated by Django 3.2.9 on 2022-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
